# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 17:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0005_add_foreignkeys_to_postalcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postalcode',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postal_codes', to=settings.CITIES_CITY_MODEL),
        ),
    ]
